import type { Metadata } from "next";

import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@udecode/cn";
import PlateThemeProvider from "./themeProvider";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          "[&_.slate-selected]:!bg-primary/20 [&_.slate-selection-area]:border [&_.slate-selection-area]:border-primary [&_.slate-selection-area]:bg-primary/10",
          fontSans.variable
        )}
        suppressHydrationWarning
      >
        <PlateThemeProvider>{children}</PlateThemeProvider>
      </body>
    </html>
  );
}
